spring.application.name=mcpjavasdk

server.port=8080

oauth.issuer=http://localhost:8080
oauth.jwks-uri=http://localhost:8080/oauth/keys

spring.ai.mcp.server.protocol=STREAMABLE
spring.ai.mcp.server.name=calculator-server
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.instructions=This streamable server provides simple calculator tools
spring.ai.mcp.server.resource-change-notification=true
spring.ai.mcp.server.tool-change-notification=true
spring.ai.mcp.server.prompt-change-notification=true
spring.ai.mcp.server.streamable-http.mcp-endpoint=/api/mcp
spring.ai.mcp.server.streamable-http.keep-alive-interval=30s